### ISSUE TITLE
Windows が生成するダイアログについて

### ISSUE THREAD

**Issue by takezou2k** [Nekomimi1958/NyanFi_x64s#1]
アプリケーションの開発お疲れ様です。
便利に使わせて頂いております。

これまでアチラにて報告してましたが
どうにも書き込みが出来なくなってしまったのでこちらにて。

### 内容
nyanfi と Windows が生成するダイアログについて
制作者の意図しないと思われる動作を確認したので報告です。

下記では一つのダイアログに注視しています。
他タイプのダイアログ挙動については未確認です。

### 環境
win11 pro 10.0.22631 ビルド 22631 ダークモード適用
nyanfi V16.25 (x64 VCL Style) win11 modern dark スタイル適用
または nyanfi V15.66 (x64)

Windows の設定(変更した覚えがないので、おそらくデフォルト値)
コントロールパネル→
すべてのコントロールパネル→
インターネットオプション→
レベルのカスタマイズ→
その他→
アプリケーションと安全でないファイルの起動→
「ダイアログを表示する(推奨)」

インターネットから何らかのアプリをダウンロード。
ネットワークドライブ(\\\\から始まる場所)に exe を設置。
その exe を叩くと
・セキュリティ警告ダイアログが出て「実行」ボタンを押すと起動
という環境

### 動作再現
この exe を nyanfi から起動しようとすると
「実行」ボタンがクリックしても反応しないダイアログが生成され
「キャンセル」を押すしかないようです。
(「実行」ボタンコントロールがグレーアウトしてるわけではない)

「キャンセル」ボタンは反応し、nyanfi ログには次のエラー表示。
>E EXEC ファイル名.exe 起動に失敗しました。

また、ダイアログは
・エクスプローラーから起動すると白い背景
・nyanfiから起動すると黒い背景
という違いがありました。

次のような動作も確認しました。
・nyanfi で exe を実行しダイアログを出す
(ダイアログが表示され nyanfi は全体的に暗くなる)
・「キャンセル」を押した場合
nyanfi にフォーカスが戻る
(暗くなった表示は元に戻る)
・他アプリウインドウをクリックしてから「キャンセル」を押した場合
ダイアログ自体は消えるが、ダイアログ表示中のフラグが解除されず nyanfi 操作不可
(暗くなった表示のまま元に戻らない)
(タスクバーの nyanfi アイコンをクリックするか、ALT+TAB で nyanfi を選択すると復帰する)

### 試したこと
nyanfi を管理者権限で実行。変化なし。
該当 exe をローカルに移動して実行。ダイアログ出ない。
上記「環境」の Windows の設定を「ダイアログ表示」以外に設定。ダイアログ出ない。

以上です。

**Comment by Nekomimi1958** [comment]
セキュリティ警告ダイアログの「実行」ボタンが効かない件について対策した v16.26 をリリースしましたので、試してみてください。

デフォルトの「Windows」以外のVCLスタイルを適用していると、NyanFi に対して表示されるシステムダイアログもスタイルの影響を受けるのですが、これによって不具合が生じているようです。

現状では NyanFi 側での対策が難しそうなので、ゾーン識別子を持つネットワーク先の実行ファイルを OpenStandard コマンドで開く場合は、子プロセスではなく、同梱の shexe.exe を介し別プロセスとして起動するようにしました。
これにより、セキュリティの警告ダイアログはVCLスタイルの影響を受けなくなり、色も変わりません。
shexe.exe は、指定した実行ファイルを起動するだけのプログラムです。
「更新の確認」や「アーカイブから更新」で更新した場合は自動的にインストールされます。

なおこれによって、セキュリティ警告ダイアログは NyanFi に対してモーダルではなくなるため、モーダル表示効果のスクリーンは表示されなくなっていますので、スクリーンが残ってしまう現象も起きなくなっています。

**Comment by takezou2k** [comment]
V16.26 にて OpenStandard で shexe.exe ありの環境で回避されているのを確認しました。
